### PR TITLE
Added FAQ for postCreateCommand

### PR DESCRIPTION
**Pull request by brun32700**
Hello @BillRaymond,

As you mentioned in the previous pull request, I have added a guide on how to make it so commands are run after a container has been created. If you could please look over my additions and let me know if something needs changing.

Also, I just wanted to say thank you for the video you created (Develop Jekyll websites in a container (including GitHub Pages). It was very helpful!

Have a great weekend!

Best regards,
brunmar

### CODE REVIEW

**Comment by brun32700** [comment]
Accidently deleted this branch, after I made a merge into the forked version. I am still trying to learn the Git functionality. Sorry about that.

**Comment by brun32700** [comment]
Can this pull request be merged, or should I just close it?

**Comment by BillRaymond** [comment]
@brun32700 sorry about the delay. #life

**Comment by BillRaymond** [comment]
@brun32700 And thank you again!

**Comment by brun32700** [comment]
@BillRaymond No worries, and thank you again for the great tutorial. Glad I could help!

**Pull request merged**
